import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const gradientStyles = {
    background: 'linear-gradient(45deg, #FF0080, #7928CA)',
    backgroundSize: '100% 100%',
    backgroundRepeat: 'no-repeat',
    minHeight: '100vh',
    animation: 'gradientAnimation 10s ease infinite', 
  };

  return (
    <html lang="en">
      <body style={gradientStyles} className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          <Navbar />
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
